### ISSUE TITLE
Unable to load .npy policy files

### ISSUE THREAD

**Issue by ianloefgren** [COHRINT/POMDP-Experiments#4]
The continuousPolicyTranslator attempts to load an .npy file using numpy.load() and is unable to do so. Traceback:

```
Traceback (most recent call last):
  File "goal_handler.py", line 296, in <module>
    gh = GoalHandler(sys.argv[1],sys.argv[2],sys.argv[3],sys.argv[4])
  File "goal_handler.py", line 116, in __init__
    self.pt = continuousPolicyTranslator(filename,hardware=True)
  File "/home/ian/catkin_ws/src/pomdp_experiments/src/continuousPolicyTranslator.py", line 53, in __init__
    self.Gamma = np.load(fileName);
  File "/home/ian/anaconda2/lib/python2.7/site-packages/numpy/lib/npyio.py", line 406, in load
    pickle_kwargs=pickle_kwargs)
  File "/home/ian/anaconda2/lib/python2.7/site-packages/numpy/lib/format.py", line 638, in read_array
    array = pickle.load(fp, **pickle_kwargs)
AttributeError: 'module' object has no attribute 'GM'
```

GM is a class contained within CPerseus.py, and is imported by the policy translator.

**Comment by ianloefgren** [comment]
Importing CPerseus, and three classes from CPerseus, including the GM class, into goal_handler.py solved the issue, though the reason for this strange scope resolution is unknown.
